/**
 * AJA INTERNATIONAL LOGISTICS — Control Tower Operational Analytics Metric Descriptors
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Control Tower Operational Analytics, Telemetry & Exception Intelligence (STEP 05.19.09)
 * Version: 1.0
 */

import {
  AnalyticsMetricDescriptor,
  AnalyticsDimensionDescriptor,
} from '../../../types/analyticsFramework';

export const CONTROL_TOWER_DIMENSIONS: AnalyticsDimensionDescriptor[] = [
  {
    id: 'category',
    labelEn: 'Exception Category',
    labelAr: 'تصنيف الاستثناء الجمركي والتشغيلي',
    sourceField: 'category',
    allowedValues: [
      'CUSTOMS_HOLD',
      'VEHICLE_BREAKDOWN',
      'COLD_CHAIN_BREACH',
      'ROUTE_DISRUPTION',
      'DOCUMENTATION_ERROR',
      'TRAFFIC_DELAY',
    ],
  },
  {
    id: 'severity',
    labelEn: 'Exception Severity',
    labelAr: 'درجة خطورة الاستثناء',
    sourceField: 'severity',
    allowedValues: ['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
  },
  {
    id: 'status',
    labelEn: 'Execution / Exception Status',
    labelAr: 'حالة الاستثناء أو معالجة التنفيذ',
    sourceField: 'status',
    allowedValues: ['OPEN', 'INVESTIGATING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'],
  },
  {
    id: 'stage',
    labelEn: 'Execution Stage',
    labelAr: 'مرحلة التنفيذ اللوجستي المباشر',
    sourceField: 'currentStage',
    allowedValues: ['PICKUP', 'IN_TRANSIT', 'PORT', 'AIRPORT', 'CUSTOMS', 'DELIVERED'],
  },
  {
    id: 'corridor',
    labelEn: 'Transport Corridor',
    labelAr: 'المسار والمنفذ اللوجستي',
    sourceField: 'originCity',
  },
  {
    id: 'carrier',
    labelEn: 'Carrier Partner',
    labelAr: 'الناقل والشريك اللوجستي',
    sourceField: 'carrierPartnerName',
  },
];

export const CONTROL_TOWER_METRICS: readonly AnalyticsMetricDescriptor[] = Object.freeze([
  {
    id: 'ct_active_operations',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.active_operations',
    labelEn: 'Active Operations',
    labelAr: 'إجمالي العمليات اللوجستية النشطة',
    descriptionEn: 'Total active logistics operations currently monitored by Control Tower.',
    descriptionAr: 'عدد العمليات والشحنات الجارية الخاضعة لمراقبة وإدارة برج التحكم.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_active_shipments',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.active_shipments',
    labelEn: 'Active Shipments',
    labelAr: 'الشحنات النشطة تحت المراقبة المباشرة',
    descriptionEn: 'Count of shipments actively executing on transport routes.',
    descriptionAr: 'عدد الشحنات التي تتحرك حالياً في المراحل التشغيلية على مسارات النقل.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_open_exceptions',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.open_exceptions',
    labelEn: 'Open Exceptions',
    labelAr: 'الاستثناءات والتنبيهات المباشرة القائمة',
    descriptionEn: 'Count of unresolved operational exceptions and incidents.',
    descriptionAr: 'عدد التنبيهات والاستثناءات القائمة التي لم يتم حسم إجراءاتها التصحيحية بعد.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'reportedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_critical_exceptions',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.critical_exceptions',
    labelEn: 'Critical Severity Exceptions',
    labelAr: 'التنبيهات حرجة الخطورة',
    descriptionEn: 'Count of active operational exceptions classified with CRITICAL severity.',
    descriptionAr: 'عدد التنبيهات عالية الأهمية والحرجة القائمة التي تتطلب تدخلاً فورياً.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'reportedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_delayed_shipments',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.delayed_shipments',
    labelEn: 'Delayed & At-Risk Shipments',
    labelAr: 'الشحنات المتأخرة والمعرضة لمخاطر التأخير',
    descriptionEn: 'Shipments with ETA variance exceeding schedule or high delay risk.',
    descriptionAr: 'عدد الشحنات المتأخرة عن الموعد المحدد أو المصنفة في نطاق مخاطر التأخير.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_sla_breaches',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.sla_breaches',
    labelEn: 'Operational SLA Breaches',
    labelAr: 'تجاوزات اتفاقيات مستوى الخدمة SLA',
    descriptionEn: 'Count of operations or milestones exceeding committed SLA duration.',
    descriptionAr: 'عدد المراحل أو العمليات التشغيلية التي تجاوزت السقف الزمني المعتمد لخدمة العملاء.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_sla_breach_rate',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.sla_breach_rate',
    labelEn: 'SLA Breach Rate (%)',
    labelAr: 'نسبة تجاوزات مستوى الخدمة SLA',
    descriptionEn: 'Percentage of active operations experiencing SLA commitments breach.',
    descriptionAr: 'النسبة المئوية للعمليات النشطة التي تعرضت لتجاوز معايير SLA.',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'ct_sla_breaches',
    denominatorMetricId: 'ct_active_operations',
    multiplier: 100,
    timeField: 'updatedAt',
    format: { valueType: 'PERCENTAGE', unit: '%', unitAr: '%', precision: 1 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_unresolved_tasks',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.unresolved_tasks',
    labelEn: 'Unresolved Workflow Tasks',
    labelAr: 'المهام التشغيلية المعلقة بانتظار الإجراء',
    descriptionEn: 'Count of pending tasks and approvals across active operations.',
    descriptionAr: 'عدد المهام التشغيلية والموافقات المعلقة لانتظار الإجراء الفني.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_completed_operations',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.completed_operations',
    labelEn: 'Completed Operations',
    labelAr: 'العمليات اللوجستية المكتملة بنجاح',
    descriptionEn: 'Total operations completed and delivered within the evaluation period.',
    descriptionAr: 'عدد الشحنات والعمليات المكتملة المسلمة للعملاء بنجاح.',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    timeField: 'updatedAt',
    format: { valueType: 'COUNT', precision: 0 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_resolution_rate',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.resolution_rate',
    labelEn: 'Exception Resolution Rate (%)',
    labelAr: 'معدل تسوية معالجة الاستثناءات (%)',
    descriptionEn: 'Percentage of reported exceptions successfully resolved.',
    descriptionAr: 'النسبة المئوية للاستثناءات والتنبيهات التي تم إغلاقها وتوثيق إجراءاتها.',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'ct_completed_operations',
    denominatorMetricId: 'ct_active_operations',
    multiplier: 100,
    timeField: 'reportedAt',
    format: { valueType: 'PERCENTAGE', unit: '%', unitAr: '%', precision: 1 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_otd_rate',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.otd_rate',
    labelEn: 'On-Time Delivery Performance (OTD %)',
    labelAr: 'نسبة الالتزام بالتسليم في الموعد OTD',
    descriptionEn: 'Percentage of completed shipments delivered on or ahead of planned ETA.',
    descriptionAr: 'نسبة الشحنات التي تم تسليمها للعميل في الوقت المحدد دون تأخير.',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'ct_completed_operations',
    denominatorMetricId: 'ct_active_operations',
    multiplier: 100,
    timeField: 'updatedAt',
    format: { valueType: 'PERCENTAGE', unit: '%', unitAr: '%', precision: 1 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
  {
    id: 'ct_logistics_health_score',
    status: 'ACTIVE',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    labelKey: 'analytics.control_tower.health_score',
    labelEn: 'Logistics Network Health Score (%)',
    labelAr: 'مؤشر صحة واستقرار المنظومة اللوجستية (%)',
    descriptionEn: 'Composite health score reflecting cold chain, route stability, and active exception impacts.',
    descriptionAr: 'المؤشر الشامل لسلامة الشحنات وسلاسل التبريد والالتزام بالمسارات.',
    valueType: 'PERCENTAGE',
    aggregationType: 'AVG',
    sourceField: 'healthScorePercent',
    timeField: 'updatedAt',
    format: { valueType: 'PERCENTAGE', unit: '%', unitAr: '%', precision: 1 },
    dimensions: CONTROL_TOWER_DIMENSIONS,
    requiredPermissions: ['control_tower:view', 'analytics:view'],
    drillDownCapable: true,
    exportable: true,
  },
]);
