/**
 * AJA INTERNATIONAL LOGISTICS — Customer Analytics Metrics
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Core Analytics Types & KPI Registry (STEP 05.19.02)
 */

import { AnalyticsMetricDescriptor } from '../../../types/analyticsFramework';

export const CUSTOMER_DIMENSIONS = [
  {
    id: 'status',
    labelEn: 'Status',
    labelAr: 'الحالة',
    sourceField: 'status',
    type: 'ENUM' as const,
    allowedValues: [
      'PROSPECT',
      'LEAD',
      'ACTIVE',
      'VIP',
      'STRATEGIC',
      'INACTIVE',
      'FORMER_CUSTOMER',
    ],
  },
  {
    id: 'customerSegment',
    labelEn: 'Segment',
    labelAr: 'شريحة العميل',
    sourceField: 'customerSegment',
    type: 'ENUM' as const,
    allowedValues: [
      'ENTERPRISE',
      'SME',
      'CORPORATE',
      'GOVERNMENT',
      'VIP',
      'RETAIL',
      'DISTRIBUTOR',
      'AGENT',
      'STRATEGIC',
      'INACTIVE',
      'PROSPECT',
      'LEAD',
      'CUSTOMER',
      'FORMER',
    ],
  },
];

export const CUSTOMER_METRICS: readonly AnalyticsMetricDescriptor[] = Object.freeze([
  {
    id: 'cust_total_customers',
    resource: 'customers',
    domain: 'CUSTOMERS',
    labelKey: 'analytics.metrics.cust_total_customers.label',
    labelEn: 'Total Customers',
    labelAr: 'إجمالي العملاء',
    descriptionEn: 'Total count of customer profiles in system',
    descriptionAr: 'إجمالي عدد ملفات العملاء بالمنظومة',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    format: {
      valueType: 'COUNT',
      unit: 'customers',
      unitAr: 'عميل',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: CUSTOMER_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'crm:customer:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'cust_active_customers',
    resource: 'customers',
    domain: 'CUSTOMERS',
    labelKey: 'analytics.metrics.cust_active_customers.label',
    labelEn: 'Active Customers',
    labelAr: 'العملاء النشطون',
    descriptionEn: 'Count of active, strategic, and VIP customers',
    descriptionAr: 'عدد العملاء النشطين والاستراتيجيين وVIP',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: ['ACTIVE', 'VIP', 'STRATEGIC'],
    },
    format: {
      valueType: 'COUNT',
      unit: 'customers',
      unitAr: 'عميل',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: CUSTOMER_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'crm:customer:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'cust_inactive_customers',
    resource: 'customers',
    domain: 'CUSTOMERS',
    labelKey: 'analytics.metrics.cust_inactive_customers.label',
    labelEn: 'Inactive Customers',
    labelAr: 'العملاء غير النشطين',
    descriptionEn: 'Count of inactive and former customers',
    descriptionAr: 'عدد العملاء غير النشطين أو السابقين',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: ['INACTIVE', 'FORMER_CUSTOMER'],
    },
    format: {
      valueType: 'COUNT',
      unit: 'customers',
      unitAr: 'عميل',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: CUSTOMER_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'crm:customer:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'cust_prospects',
    resource: 'customers',
    domain: 'CUSTOMERS',
    labelKey: 'analytics.metrics.cust_prospects.label',
    labelEn: 'Prospects & Leads',
    labelAr: 'العملاء المحتملون والفرص',
    descriptionEn: 'Count of prospect and lead profiles',
    descriptionAr: 'عدد العملاء المحتملين والفرص البيعية',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: ['PROSPECT', 'LEAD'],
    },
    format: {
      valueType: 'COUNT',
      unit: 'prospects',
      unitAr: 'عميل محتمل',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: CUSTOMER_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'crm:customer:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
]);
