/**
 * AJA INTERNATIONAL LOGISTICS — Finance Domain Analytics Metrics Descriptor Set
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Financial Analytics, Multi-Currency Normalization & C-Suite Cockpit (STEP 05.19.08)
 */

import { AnalyticsMetricDescriptor, AnalyticsDimensionDescriptor } from '../../../types/analyticsFramework';

export const FINANCE_DIMENSIONS: readonly AnalyticsDimensionDescriptor[] = Object.freeze([
  {
    id: 'category',
    labelEn: 'Account Category',
    labelAr: 'فئة الحساب',
    sourceField: 'category',
    type: 'STRING' as const,
  },
  {
    id: 'accountCode',
    labelEn: 'Account Code',
    labelAr: 'رمز الحساب',
    sourceField: 'accountCode',
    type: 'STRING' as const,
  },
  {
    id: 'branchId',
    labelEn: 'Branch',
    labelAr: 'الفرع',
    sourceField: 'branchId',
    type: 'STRING' as const,
  },
  {
    id: 'costCenterCode',
    labelEn: 'Cost Center',
    labelAr: 'مركز التكلفة',
    sourceField: 'costCenterCode',
    type: 'STRING' as const,
  },
  {
    id: 'currency',
    labelEn: 'Transaction Currency',
    labelAr: 'عملة المعاملة',
    sourceField: 'currencyCode',
    type: 'STRING' as const,
  },
  {
    id: 'status',
    labelEn: 'Financial Status',
    labelAr: 'الحالة المالية',
    sourceField: 'status',
    type: 'STRING' as const,
  },
  {
    id: 'agingBucket',
    labelEn: 'AR Aging Bucket',
    labelAr: 'شرائح تعمير الذمم',
    sourceField: 'agingBucket',
    type: 'STRING' as const,
  },
]);

export const FINANCE_METRICS: readonly AnalyticsMetricDescriptor[] = Object.freeze([
  {
    id: 'fin_invoiced_revenue',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.invoiced_revenue',
    labelEn: 'Total Billed Invoiced Revenue',
    labelAr: 'إجمالي إيرادات الفواتير المفلترة',
    descriptionEn: 'Total invoiced revenue issued across customer accounts',
    descriptionAr: 'إجمالي المبالغ المفصلة بالفواتير الصادرة للعملاء',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'totalAmountSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'issueDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_recognized_revenue',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.recognized_revenue',
    labelEn: 'Recognized Revenue (P&L)',
    labelAr: 'الإيرادات المعترف بها (قائمة الدخل)',
    descriptionEn: 'Earned revenue posted to General Ledger operating revenue accounts',
    descriptionAr: 'الإيرادات المستحقة والمسجلة بدفتر الأستاذ الحسابي للأعمال المنجزة',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'ytdRevenueSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'postingDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_cash_collected',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.cash_collected',
    labelEn: 'Cash Collected & Settled',
    labelAr: 'المقبوضات والكاش المحصل فعلياً',
    descriptionEn: 'Actual payments collected and settled into bank/treasury accounts',
    descriptionAr: 'المدفوعات والمبالغ المحصلة والمستقرة بالخزينة والمصارف',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'paidAmountSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'updatedAt',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_outstanding_ar',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.outstanding_ar',
    labelEn: 'Outstanding Accounts Receivable',
    labelAr: 'الذمم المدينة والتحصيلات المستحقة',
    descriptionEn: 'Total uncollected balance due from customer accounts',
    descriptionAr: 'إجمالي المبالغ المتبقية والذمم غير المحصلة من العملاء',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'balanceDueSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'dueDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_operating_expenses',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.operating_expenses',
    labelEn: 'Operating Expenses (OPEX)',
    labelAr: 'المصروفات التشغيلية الإدارية',
    descriptionEn: 'General & administrative operating expenditures',
    descriptionAr: 'إجمالي المصاريف العمومية والإدارية التشغيلية',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'ytdOperatingExpensesSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'postingDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_direct_cost',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.direct_cost',
    labelEn: 'Direct Freight Logistics Cost (COGS)',
    labelAr: 'تكاليف الخدمات اللوجستية المباشرة',
    descriptionEn: 'Direct cost of goods sold for carrier transport, fuel & warehousing',
    descriptionAr: 'التكاليف المباشرة للخدمات اللوجستية والنقل والوقود والتخزين',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'ytdCostOfSalesSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'postingDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_gross_profit',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.gross_profit',
    labelEn: 'Gross Logistics Profit',
    labelAr: 'مجمل الربح اللوجستي',
    descriptionEn: 'Net margin generated from recognized revenue minus direct freight costs',
    descriptionAr: 'الفارق الصافي بين الإيرادات المعترف بها والتكاليف المباشرة',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'grossProfitSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'postingDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'CONFIDENTIAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_gross_margin',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.gross_margin',
    labelEn: 'Gross Margin Percentage',
    labelAr: 'نسبة مجمل الربح اللوجستي',
    descriptionEn: 'Ratio of gross profit over recognized revenue expressed as percentage',
    descriptionAr: 'نسبة مجمل الربح من إجمالي الإيرادات المعترف بها',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'fin_gross_profit',
    denominatorMetricId: 'fin_recognized_revenue',
    multiplier: 100,
    format: {
      valueType: 'PERCENTAGE',
      unit: '%',
      unitAr: '%',
      precision: 2,
    },
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'CONFIDENTIAL',
    drillDownCapable: false,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_ar_overdue',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.ar_overdue',
    labelEn: 'Overdue Accounts Receivable',
    labelAr: 'الذمم المتأخرة عن تاريخ الاستحقاق',
    descriptionEn: 'Unpaid invoice balance past the contractual due date',
    descriptionAr: 'إجمالي الذمم غير المحصلة ومتجاوزة تاريخ الاستحقاق المكتوب',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'overdueBalanceSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'dueDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'fin_ar_current',
    resource: 'finance',
    domain: 'FINANCE',
    labelKey: 'analytics.finance.ar_current',
    labelEn: 'Current Non-Overdue AR',
    labelAr: 'الذمم الجارية ضمن فترة الاستحقاق',
    descriptionEn: 'Active unpaid receivables within contractual credit terms',
    descriptionAr: 'الذمم القائمة غير المحصلة ولكن ضمن فترة الائتمان المسموحة',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'currentBalanceSAR',
    format: {
      valueType: 'CURRENCY',
      defaultCurrency: 'SAR',
      precision: 2,
      currencyPolicy: 'BASE_CURRENCY_NORMALIZED',
    },
    timeField: 'dueDate',
    dimensions: Array.from(FINANCE_DIMENSIONS),
    requiredPermissions: ['finance:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
]);
