/**
 * AJA INTERNATIONAL LOGISTICS — Quote Analytics Metrics
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Core Analytics Types & KPI Registry (STEP 05.19.02)
 */

import { AnalyticsMetricDescriptor } from '../../../types/analyticsFramework';

export const QUOTE_DIMENSIONS = [
  {
    id: 'status',
    labelEn: 'Status',
    labelAr: 'الحالة',
    sourceField: 'status',
    type: 'ENUM' as const,
    allowedValues: [
      'NEW',
      'UNDER_REVIEW',
      'CONTACTED',
      'QUOTE_SENT',
      'NEGOTIATING',
      'AGREED',
      'REJECTED',
      'CLOSED',
    ],
  },
  {
    id: 'serviceType',
    labelEn: 'Service Type',
    labelAr: 'نوع الخدمة',
    sourceField: 'serviceType',
    type: 'ENUM' as const,
    allowedValues: [
      'SEA_FREIGHT',
      'LAND_FREIGHT',
      'CUSTOMS_CLEARANCE',
      'WAREHOUSING',
      'DOOR_TO_DOOR',
    ],
  },
  {
    id: 'currency',
    labelEn: 'Currency',
    labelAr: 'العملة',
    sourceField: 'currency',
    type: 'STRING' as const,
  },
];

export const QUOTE_METRICS: readonly AnalyticsMetricDescriptor[] = Object.freeze([
  {
    id: 'quote_total_quotes',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_total_quotes.label',
    labelEn: 'Total Quotes',
    labelAr: 'إجمالي العروض',
    descriptionEn: 'Total count of quote requests',
    descriptionAr: 'إجمالي عدد طلبات العروض',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    format: {
      valueType: 'COUNT',
      unit: 'quotes',
      unitAr: 'عرض',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'quote_pending_quotes',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_pending_quotes.label',
    labelEn: 'Pending Quotes',
    labelAr: 'العروض المعلقة',
    descriptionEn: 'Count of active quotes under review or negotiation',
    descriptionAr: 'عدد العروض القائمة قيد المراجعة أو التفاوض',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: ['NEW', 'UNDER_REVIEW', 'CONTACTED', 'QUOTE_SENT', 'NEGOTIATING'],
    },
    format: {
      valueType: 'COUNT',
      unit: 'quotes',
      unitAr: 'عرض',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'quote_accepted_quotes',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_accepted_quotes.label',
    labelEn: 'Accepted Quotes',
    labelAr: 'العروض المقبولة',
    descriptionEn: 'Count of agreed/accepted quotes',
    descriptionAr: 'عدد العروض المقبولة والموافق عليها',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: 'AGREED',
    },
    format: {
      valueType: 'COUNT',
      unit: 'quotes',
      unitAr: 'عرض',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'quote_rejected_quotes',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_rejected_quotes.label',
    labelEn: 'Rejected Quotes',
    labelAr: 'العروض المرفوضة',
    descriptionEn: 'Count of rejected quotes',
    descriptionAr: 'عدد العروض المرفوضة',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: 'REJECTED',
    },
    format: {
      valueType: 'COUNT',
      unit: 'quotes',
      unitAr: 'عرض',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'quote_conversion_rate',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_conversion_rate.label',
    labelEn: 'Quote Conversion Rate',
    labelAr: 'نسبة تحويل العروض',
    descriptionEn: 'Percentage of accepted quotes over total quotes',
    descriptionAr: 'نسبة العروض المقبولة من إجمالي العروض',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'quote_accepted_quotes',
    denominatorMetricId: 'quote_total_quotes',
    multiplier: 100,
    format: {
      valueType: 'PERCENTAGE',
      unit: '%',
      precision: 2,
      suffix: '%',
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'quote_offered_value',
    resource: 'quotes',
    domain: 'SALES',
    labelKey: 'analytics.metrics.quote_offered_value.label',
    labelEn: 'Total Offered Quote Value',
    labelAr: 'إجمالي قيمة العروض المقدمة',
    descriptionEn: 'Sum of offered quote prices grouped by currency',
    descriptionAr: 'مجموع أصل أسعار العروض المعروضة مقسمة حسب العملة',
    valueType: 'CURRENCY',
    aggregationType: 'SUM',
    sourceField: 'offeredPrice',
    format: {
      valueType: 'CURRENCY',
      currencyPolicy: 'CURRENCY_GROUPED',
      defaultCurrency: 'SAR',
      precision: 2,
    },
    timeField: 'createdAt',
    dimensions: QUOTE_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'sales:quote:view'],
    fieldSecurityClassification: 'RESTRICTED',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
]);
