/**
 * AJA INTERNATIONAL LOGISTICS — Shipment Analytics Metrics
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Core Analytics Types & KPI Registry (STEP 05.19.02)
 */

import { AnalyticsMetricDescriptor } from '../../../types/analyticsFramework';

export const SHIPMENT_DIMENSIONS = [
  {
    id: 'status',
    labelEn: 'Status',
    labelAr: 'الحالة',
    sourceField: 'status',
    type: 'ENUM' as const,
    allowedValues: [
      'RECEIVED',
      'BOOKING_CONFIRMED',
      'PREPARING',
      'LOADING',
      'IN_TRANSIT',
      'ARRIVED_AT_PORT',
      'DEPARTURE_CUSTOMS',
      'CUSTOMS_CLEARANCE',
      'OUT_FOR_DELIVERY',
      'DELIVERED',
      'CANCELLED',
    ],
  },
  {
    id: 'serviceType',
    labelEn: 'Service Type',
    labelAr: 'نوع الخدمة',
    sourceField: 'serviceType',
    type: 'ENUM' as const,
    allowedValues: [
      'SEA_FREIGHT',
      'LAND_FREIGHT',
      'CUSTOMS_CLEARANCE',
      'WAREHOUSING',
      'DOOR_TO_DOOR',
    ],
  },
  {
    id: 'origin',
    labelEn: 'Origin',
    labelAr: 'المصدر',
    sourceField: 'origin',
    type: 'STRING' as const,
  },
  {
    id: 'destination',
    labelEn: 'Destination',
    labelAr: 'الوجهة',
    sourceField: 'destination',
    type: 'STRING' as const,
  },
  {
    id: 'corridor',
    labelEn: 'Trade Corridor',
    labelAr: 'الممر التجاري',
    sourceField: 'corridor',
    type: 'STRING' as const,
  },
];

export const SHIPMENT_METRICS: readonly AnalyticsMetricDescriptor[] = Object.freeze([
  {
    id: 'shp_total_shipments',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_total_shipments.label',
    labelEn: 'Total Shipments',
    labelAr: 'إجمالي الشحنات',
    descriptionEn: 'Total count of all tracked shipments',
    descriptionAr: 'العدد الإجمالي لجميع الشحنات المسجلة',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    format: {
      valueType: 'COUNT',
      unit: 'shipments',
      unitAr: 'شحنة',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'shp_active_shipments',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_active_shipments.label',
    labelEn: 'Active Shipments',
    labelAr: 'الشحنات النشطة',
    descriptionEn: 'Count of active shipments currently in progress or transit',
    descriptionAr: 'عدد الشحنات القائمة جاري تنفيذها أو نقلها',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: [
        'RECEIVED',
        'BOOKING_CONFIRMED',
        'PREPARING',
        'LOADING',
        'IN_TRANSIT',
        'ARRIVED_AT_PORT',
        'DEPARTURE_CUSTOMS',
        'CUSTOMS_CLEARANCE',
        'OUT_FOR_DELIVERY',
      ],
    },
    format: {
      valueType: 'COUNT',
      unit: 'shipments',
      unitAr: 'شحنة',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'shp_delivered_shipments',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_delivered_shipments.label',
    labelEn: 'Delivered Shipments',
    labelAr: 'الشحنات المسلّمة',
    descriptionEn: 'Total count of successfully delivered shipments',
    descriptionAr: 'إجمالي عدد الشحنات التي تم تسليمها بنجاح',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: 'DELIVERED',
    },
    format: {
      valueType: 'COUNT',
      unit: 'shipments',
      unitAr: 'شحنة',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'shp_cancelled_shipments',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_cancelled_shipments.label',
    labelEn: 'Cancelled Shipments',
    labelAr: 'الشحنات الملغاة',
    descriptionEn: 'Count of cancelled shipments',
    descriptionAr: 'عدد الشحنات التي تم إلغاؤها',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    sourceField: 'id',
    filterConditions: {
      status: 'CANCELLED',
    },
    format: {
      valueType: 'COUNT',
      unit: 'shipments',
      unitAr: 'شحنة',
      precision: 0,
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'shp_delivery_completion_rate',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_delivery_completion_rate.label',
    labelEn: 'Delivery Completion Rate',
    labelAr: 'نسبة إنجاز التسليم',
    descriptionEn: 'Percentage of delivered shipments over total shipments',
    descriptionAr: 'نسبة الشحنات المسلمة بالنسبة إلى إجمالي الشحنات',
    valueType: 'PERCENTAGE',
    aggregationType: 'RATIO',
    numeratorMetricId: 'shp_delivered_shipments',
    denominatorMetricId: 'shp_total_shipments',
    multiplier: 100,
    format: {
      valueType: 'PERCENTAGE',
      unit: '%',
      precision: 2,
      suffix: '%',
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
  {
    id: 'shp_total_weight_kg',
    resource: 'shipments',
    domain: 'LOGISTICS',
    labelKey: 'analytics.metrics.shp_total_weight_kg.label',
    labelEn: 'Total Weight (kg)',
    labelAr: 'إجمالي الوزن (كجم)',
    descriptionEn: 'Sum of shipment weights in kilograms',
    descriptionAr: 'مجموع أوزان الشحنات بالكيلوجرام',
    valueType: 'NUMBER',
    aggregationType: 'SUM',
    sourceField: 'weightKg',
    format: {
      valueType: 'NUMBER',
      unit: 'kg',
      unitAr: 'كجم',
      precision: 2,
    },
    timeField: 'createdAt',
    dimensions: SHIPMENT_DIMENSIONS,
    requiredPermissions: ['analytics:view', 'shipping:shipment:view'],
    fieldSecurityClassification: 'INTERNAL',
    drillDownCapable: true,
    exportable: true,
    status: 'ACTIVE',
  },
]);
