import { AIAgentMetadata, AIAgentRole } from './types';

export class AgentManagerService {
  private static readonly AGENTS_CATALOG: AIAgentMetadata[] = [
    {
      id: 'EXECUTIVE_ADVISOR',
      nameEn: 'Executive AI Advisor',
      nameAr: 'المستشار التنفيذي الذكي',
      department: 'Executive Board & CEO Office',
      description: 'Strategic intelligence, enterprise growth recommendations, M&A insights, and executive summaries.',
      systemPrompt: 'You are the Executive AI Advisor for AJA Logistics. Provide strategic, high-level business intelligence, EBITDA optimization insights, and executive summaries.',
      capabilities: ['Strategic Planning', 'EBITDA Analytics', 'Growth Forecasting', 'Risk Synthesis'],
      allowedTools: ['get_executive_kpis', 'get_financial_ledger', 'get_market_trends'],
      securityLevel: 'RESTRICTED',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'FINANCE_ANALYST',
      nameEn: 'Finance AI Analyst',
      nameAr: 'محلل المالية الذكي',
      department: 'Finance & Accounting',
      description: 'Automated double-entry reconciliation, revenue recognition, tax analysis, and budget variance detection.',
      systemPrompt: 'You are the Finance AI Analyst. Analyze ledger entries, tax compliance (VAT/GST), and accounting variance.',
      capabilities: ['Double Entry Auditing', 'Tax Reconciliation', 'Margin Analysis', 'Budget Variance'],
      allowedTools: ['query_ledger', 'calculate_tax', 'generate_pnl'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'TREASURY_ANALYST',
      nameEn: 'Treasury AI Analyst',
      nameAr: 'محلل الخزينة وإدارة السيولة الذكي',
      department: 'Treasury & Cash Management',
      description: 'Liquidity forecasting, bank account balancing, foreign exchange (FX) exposure, and cash position optimization.',
      systemPrompt: 'You are the Treasury AI Analyst. Monitor corporate cash flow, bank account liquidity ratios, and FX risk.',
      capabilities: ['Liquidity Forecasting', 'FX Risk Analysis', 'Bank Reconciliation', 'Intercompany Transfers'],
      allowedTools: ['get_cash_position', 'forecast_liquidity', 'get_fx_rates'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'SALES_ASSISTANT',
      nameEn: 'Sales AI Assistant',
      nameAr: 'مساعد المبيعات والعقود الذكي',
      department: 'Sales & Commercial',
      description: 'Lead scoring, proposal drafting, quote conversion forecasting, and competitor win-loss analysis.',
      systemPrompt: 'You are the Sales AI Assistant. Assist commercial managers with deal pipeline optimization and quote proposals.',
      capabilities: ['Lead Scoring', 'Proposal Generation', 'Win-Loss Analytics', 'Tariff Matching'],
      allowedTools: ['get_crm_leads', 'generate_quote_proposal', 'get_pricing_matrices'],
      securityLevel: 'PUBLIC',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'MARKETING_ASSISTANT',
      nameEn: 'Marketing AI Assistant',
      nameAr: 'مساعد التسويق الرقمي الذكي',
      department: 'Marketing & Brand',
      description: 'Campaign ROI measurement, customer segment profiling, and content generation for logistics services.',
      systemPrompt: 'You are the Marketing AI Assistant. Help craft omnichannel logistics campaigns and measure ROI.',
      capabilities: ['Campaign ROI', 'Customer Profiling', 'Copy Generation', 'Channel Analytics'],
      allowedTools: ['get_campaign_metrics', 'segment_customers'],
      securityLevel: 'PUBLIC',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'CUSTOMER_SUPPORT',
      nameEn: 'Customer Support AI',
      nameAr: 'مساعد دعم العملاء الذكي',
      department: 'Customer Service & Care',
      description: '24/7 multilingual shipment tracking, ticket resolution, complaint triage, and FAQ assistance.',
      systemPrompt: 'You are Customer Support AI. Assist clients with tracking, document requirements, and status updates politely in Arabic and English.',
      capabilities: ['24/7 Support', 'Shipment Tracking', 'Ticket Resolution', 'FAQ Guidance'],
      allowedTools: ['get_shipment_status', 'get_customer_shipments', 'get_required_documents'],
      securityLevel: 'PUBLIC',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'OPERATIONS_COORDINATOR',
      nameEn: 'Operations AI Coordinator',
      nameAr: 'منسق العمليات والتحكم اللوجستي الذكي',
      department: 'Global Control Tower',
      description: 'End-to-end shipment routing, exception handling, port delay mitigation, and carrier SLA monitoring.',
      systemPrompt: 'You are the Operations AI Coordinator. Oversee shipment milestones, port congestion, and SLA compliance.',
      capabilities: ['Milestone Monitoring', 'Port Congestion Alerts', 'Carrier SLA Tracking', 'Exception Rerouting'],
      allowedTools: ['get_control_tower_status', 'reroute_shipment', 'get_carrier_slas'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'WAREHOUSE_ASSISTANT',
      nameEn: 'Warehouse AI Assistant',
      nameAr: 'مساعد المستودعات والتخزين الذكي',
      department: 'Smart Warehousing & WMS/WES',
      description: 'Dynamic slotting optimization, putaway planning, ASN inbound verification, and picker route planning.',
      systemPrompt: 'You are the Warehouse AI Assistant. Optimize bin locations, inbound receiving, and inventory turnover.',
      capabilities: ['Dynamic Slotting', 'Inbound ASN Inspection', 'Putaway Recommendation', 'Pick Route Optimization'],
      allowedTools: ['get_warehouse_bins', 'optimize_slotting', 'verify_asn'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'FLEET_COORDINATOR',
      nameEn: 'Fleet AI Coordinator',
      nameAr: 'منسق الأسطول والنقل البري الذكي',
      department: 'Transportation & Fleet Management',
      description: 'Vehicle routing, telematics analysis, fuel consumption reduction, and predictive maintenance dispatch.',
      systemPrompt: 'You are the Fleet AI Coordinator. Optimize truck dispatching, route efficiency, driver schedules, and fuel usage.',
      capabilities: ['Route Planning', 'Telematics Analytics', 'Predictive Maintenance', 'Fuel Optimization'],
      allowedTools: ['get_fleet_status', 'plan_truck_route', 'check_telematics'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'PROCUREMENT_ASSISTANT',
      nameEn: 'Procurement AI Assistant',
      nameAr: 'مساعد المشتريات والشركاء الذكي',
      department: 'Procurement & Vendor Management',
      description: 'Supplier contract evaluation, 3PL tender scoring, purchase order matching, and vendor SLA scoring.',
      systemPrompt: 'You are the Procurement AI Assistant. Evaluate vendor proposals, negotiate terms, and track supplier SLAs.',
      capabilities: ['3PL Tender Scoring', 'Contract Matching', 'Supplier Risk Analysis', 'Purchase Order Approval'],
      allowedTools: ['score_3pl_tender', 'get_vendor_contracts', 'evaluate_po'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'HR_ASSISTANT',
      nameEn: 'HR AI Assistant',
      nameAr: 'مساعد الموارد البشرية والتدريب الذكي',
      department: 'Human Resources & Talent',
      description: 'Staff onboarding, policy Q&A, shift scheduling, training recommendations, and driver compliance tracking.',
      systemPrompt: 'You are the HR AI Assistant. Assist HR teams with employee onboarding, driver certification, and policy guidance.',
      capabilities: ['Employee Onboarding', 'Policy Guidance', 'Shift Scheduling', 'Certification Tracking'],
      allowedTools: ['get_employee_records', 'verify_driver_licenses', 'search_hr_policies'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'LEGAL_ASSISTANT',
      nameEn: 'Legal AI Assistant',
      nameAr: 'المستشار القانوني والعقود الذكي',
      department: 'Legal Affairs',
      description: 'Contract clause extraction, liability limit checking, indemnity clause analysis, and regulatory legal review.',
      systemPrompt: 'You are the Legal AI Assistant. Review logistics contracts, bill of lading terms, and legal liability limits.',
      capabilities: ['Contract Clause Review', 'Liability Risk Analysis', 'Incoterms Validation', 'Dispute Synthesis'],
      allowedTools: ['review_contract_clauses', 'check_incoterms', 'verify_liability'],
      securityLevel: 'RESTRICTED',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'COMPLIANCE_ASSISTANT',
      nameEn: 'Compliance AI Assistant',
      nameAr: 'مساعد الالتزام والجمارك الذكي',
      department: 'Governance & Compliance',
      description: 'Fasah customs declaration checks, HS Code classification, ISO audit compliance, and trade regulation tracking.',
      systemPrompt: 'You are the Compliance AI Assistant. Verify Saudi Customs (Fasah) compliance, HS Code tariffs, and ISO standards.',
      capabilities: ['HS Code Classification', 'Customs Pre-Validation', 'ISO Audit Verification', 'Trade Regulation Alerts'],
      allowedTools: ['classify_hs_code', 'verify_customs_docs', 'check_iso_controls'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'RISK_INTELLIGENCE',
      nameEn: 'Risk Intelligence AI',
      nameAr: 'ذكاء إدارة المخاطر المؤسسية',
      department: 'Enterprise Risk Management (ERM)',
      description: 'Supply chain disruption prediction, geopolitical risk scoring, currency exposure risk, and credit risk assessment.',
      systemPrompt: 'You are Risk Intelligence AI. Calculate risk heatmaps, mitigation pathways, and supply chain vulnerability indices.',
      capabilities: ['Disruption Prediction', 'Geopolitical Risk Scoring', 'Credit Risk Matrix', 'Heatmap Synthesis'],
      allowedTools: ['get_risk_register', 'calculate_risk_score', 'run_risk_simulation'],
      securityLevel: 'RESTRICTED',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'SECURITY_ASSISTANT',
      nameEn: 'Security AI Assistant',
      nameAr: 'مساعد الأمن السيبراني والسلامة الذكي',
      department: 'Cybersecurity & Information Security',
      description: 'Prompt injection defense, data leak detection, SOC2/ISO27001 audit validation, and threat intelligence monitoring.',
      systemPrompt: 'You are Security AI Assistant. Enforce security standards, inspect API access logs, and block unauthorized threats.',
      capabilities: ['Threat Detection', 'Data Leak Prevention', 'Prompt Injection Shield', 'SOC2 Log Auditing'],
      allowedTools: ['audit_security_logs', 'check_pii_exposure', 'verify_mfa_status'],
      securityLevel: 'RESTRICTED',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'ERP_ASSISTANT',
      nameEn: 'ERP AI Assistant',
      nameAr: 'مساعد نظام ERP التكاملي الذكي',
      department: 'Enterprise Resource Planning',
      description: 'SAP/Oracle sync monitoring, general ledger posting verification, purchase order tracking, and master data alignment.',
      systemPrompt: 'You are the ERP AI Assistant. Coordinate bidirectional SAP/Oracle data flows, master data records, and GL postings.',
      capabilities: ['SAP Sync Auditing', 'GL Posting Validation', 'Master Data Matching', 'ERP Exception Triaging'],
      allowedTools: ['get_erp_sync_status', 'validate_gl_posting', 'query_mdm_records'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'CRM_ASSISTANT',
      nameEn: 'CRM AI Assistant',
      nameAr: 'مساعد إدارة علاقات العملاء CRM الذكي',
      department: 'Customer Relationship Management',
      description: 'Customer 360 profile synthesis, sentiment tracking, account churn prediction, and interaction summary generation.',
      systemPrompt: 'You are the CRM AI Assistant. Provide 360-degree customer insights, sentiment tracking, and account health scores.',
      capabilities: ['Customer 360 Insights', 'Sentiment Analysis', 'Churn Risk Scoring', 'Account Health Matrix'],
      allowedTools: ['get_customer_360', 'predict_churn', 'summarize_crm_timeline'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'DOCUMENT_INTELLIGENCE',
      nameEn: 'Document Intelligence AI',
      nameAr: 'ذكاء تحليل واستخراج المستندات الرقمية',
      department: 'Document Operations & OCR',
      description: 'Automated OCR, entity extraction, document classification, and validation for Bills of Lading, Invoices, and Customs papers.',
      systemPrompt: 'You are Document Intelligence AI. Extract structured JSON fields from shipping documents, invoices, and customs bills.',
      capabilities: ['OCR Extraction', 'Bill of Lading Parsing', 'Invoice Entity Matching', 'Customs Document Audit'],
      allowedTools: ['extract_document_entities', 'validate_ocr_data', 'match_invoice_po'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'BUSINESS_INTELLIGENCE',
      nameEn: 'Business Intelligence AI',
      nameAr: 'ذكاء الأعمال والتقارير الاستراتيجية',
      department: 'BI & Analytics Center',
      description: 'Automated executive chart generation, SQL data querying, trend anomaly detection, and operational KPI reporting.',
      systemPrompt: 'You are Business Intelligence AI. Synthesize complex logistics datasets into clear visual trends, KPIs, and charts.',
      capabilities: ['KPI Dashboard Synthesis', 'SQL Query Generation', 'Anomaly Trend Detection', 'Automated Report Building'],
      allowedTools: ['run_bi_query', 'get_kpi_dashboards', 'detect_anomalies'],
      securityLevel: 'CONFIDENTIAL',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'DEVELOPER_ASSISTANT',
      nameEn: 'Developer AI Assistant',
      nameAr: 'مساعد المطورين والهندسة البرمجية',
      department: 'Software Engineering & IT',
      description: 'API SDK integration help, GraphQL schema checking, unit test generation, and code refactoring suggestions.',
      systemPrompt: 'You are the Developer AI Assistant. Help engineers write TypeScript code, debug API routes, and maintain code quality.',
      capabilities: ['Code Refactoring', 'API Docs Explanation', 'Unit Test Generation', 'Type Checking'],
      allowedTools: ['inspect_api_spec', 'generate_unit_test', 'check_code_lint'],
      securityLevel: 'PUBLIC',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
    {
      id: 'DEVOPS_ASSISTANT',
      nameEn: 'DevOps AI Assistant',
      nameAr: 'مساعد البنية التحتية والتشغيل الذكي',
      department: 'DevOps & Cloud Infrastructure',
      description: 'Cloud Run deployment status, database health checks, rate limiter monitoring, and CI/CD pipeline automation.',
      systemPrompt: 'You are the DevOps AI Assistant. Monitor container health, latency SLOs, database queries, and deployment status.',
      capabilities: ['Cloud Run Monitoring', 'Database Health Check', 'Latency SLO Auditing', 'Container Logs Analysis'],
      allowedTools: ['get_system_health', 'check_cloud_run_status', 'inspect_logs'],
      securityLevel: 'RESTRICTED',
      modelPreference: 'gemini-3.6-flash',
      status: 'ACTIVE',
    },
  ];

  public static getAllAgents(): AIAgentMetadata[] {
    return this.AGENTS_CATALOG;
  }

  public static getAgentByRole(role: AIAgentRole): AIAgentMetadata | undefined {
    return this.AGENTS_CATALOG.find((a) => a.id === role);
  }

  public static listAgentsByDepartment(dept: string): AIAgentMetadata[] {
    return this.AGENTS_CATALOG.filter((a) => a.department.toLowerCase().includes(dept.toLowerCase()));
  }
}
