/**
 * AJA INTERNATIONAL LOGISTICS — Canonical System Report Templates
 * Parent Phase: STEP 05.19 — Enterprise Reporting, Executive Analytics & Data Intelligence Engine
 * Module: Parameterized Report Builder, PDF Summary Generation & Scheduled Reports (STEP 05.19.10)
 */

import { ReportDefinition } from '../../types/reportFramework';

export const SYSTEM_REPORT_TEMPLATES: readonly ReportDefinition[] = Object.freeze([
  {
    id: 'rpt_tpl_exec_logistics_summary',
    nameEn: 'Executive Logistics Operations Summary',
    nameAr: 'الملخص التنفيذي للعمليات اللوجستية',
    descriptionEn: 'High-level executive overview of active shipments, delivery completion, and SLA performance.',
    descriptionAr: 'نظرة شاملة للإدارة العليا عن الشحنات النشطة ونسب التسليم والالتزام بمستوى الخدمة.',
    resource: 'shipments',
    domain: 'EXECUTIVE',
    metricIds: ['shp_total_shipments', 'shp_active_shipments', 'shp_delivered_shipments', 'shp_delivery_completion_rate'],
    dimensions: ['serviceType', 'status'],
    timeSeries: {
      enabled: true,
      timeBucket: 'DAY',
      timeField: 'createdAt',
    },
    parameters: [
      {
        id: 'dateRange',
        nameEn: 'Evaluation Period',
        nameAr: 'فترة التقييم',
        type: 'DATE_RANGE',
        targetFilterKey: 'dateRange',
        required: false,
      },
      {
        id: 'serviceType',
        nameEn: 'Service Category',
        nameAr: 'نوع الخدمة اللوجستية',
        type: 'SELECT',
        targetFilterKey: 'serviceType',
        required: false,
        allowedValues: [
          { value: 'AIR_FREIGHT', labelEn: 'Air Freight', labelAr: 'شحن جوي' },
          { value: 'SEA_FREIGHT', labelEn: 'Sea Freight', labelAr: 'شحن بحري' },
          { value: 'LAND_TRANSPORT', labelEn: 'Land Transport', labelAr: 'نقل بري' },
          { value: 'CUSTOMS_CLEARANCE', labelEn: 'Customs Clearance', labelAr: 'تخليص جمركي' },
          { value: 'WAREHOUSING', labelEn: 'Warehousing', labelAr: 'تخزين وسلاسل إمداد' },
        ],
      },
    ],
    sections: [
      {
        id: 'sec_kpi',
        type: 'KPI_SUMMARY',
        titleEn: 'Executive Key Performance Indicators',
        titleAr: 'مؤشرات الأداء الرئيسية للإدارة',
        metricIds: ['shp_total_shipments', 'shp_active_shipments', 'shp_delivered_shipments', 'shp_delivery_completion_rate'],
      },
      {
        id: 'sec_grouped_service',
        type: 'GROUPED_TABLE',
        titleEn: 'Performance Breakdown by Service Line',
        titleAr: 'تحليل الأداء حسب خطوط الخدمة',
        dimension: 'serviceType',
      },
      {
        id: 'sec_ts_daily',
        type: 'TIME_SERIES',
        titleEn: 'Daily Shipment Execution Velocity',
        titleAr: 'معدل حركة الشحنات اليومية',
        timeBucket: 'DAY',
      },
    ],
    outputFormats: ['PDF', 'CSV', 'XLSX'],
    requiredPermissions: ['analytics:view', 'reports:view'],
    visibility: 'SYSTEM',
    status: 'ACTIVE',
    createdBy: 'system_admin',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rpt_tpl_customer_performance',
    nameEn: 'Customer Account Intelligence & Shipping Performance',
    nameAr: 'تقرير أداء الحسابات التجارية للعملاء',
    descriptionEn: 'Detailed analytics on active enterprise customer accounts, shipment volumes, and SLA delivery rates.',
    descriptionAr: 'تحليلات تفصيلية لحسابات العملاء وأحجام الشحن ومعدلات الالتزام بمواعيد التسليم.',
    resource: 'customers',
    domain: 'CUSTOMER',
    metricIds: ['cust_total_customers', 'cust_active_customers', 'cust_inactive_customers', 'cust_prospects'],
    dimensions: ['status', 'customerSegment'],
    parameters: [
      {
        id: 'dateRange',
        nameEn: 'Date Range',
        nameAr: 'النطاق الزمني',
        type: 'DATE_RANGE',
        targetFilterKey: 'dateRange',
      },
    ],
    sections: [
      {
        id: 'sec_cust_kpi',
        type: 'KPI_SUMMARY',
        titleEn: 'Customer Account Portfolio KPIs',
        titleAr: 'مؤشرات محفظة حسابات العملاء',
        metricIds: ['cust_total_customers', 'cust_active_customers', 'cust_inactive_customers', 'cust_prospects'],
      },
      {
        id: 'sec_cust_segment',
        type: 'GROUPED_TABLE',
        titleEn: 'Distribution Across Customer Segments',
        titleAr: 'التوزيع حسب شرائح العملاء',
        dimension: 'customerSegment',
      },
    ],
    outputFormats: ['PDF', 'CSV', 'XLSX'],
    requiredPermissions: ['analytics:view', 'crm:customer:view'],
    visibility: 'SYSTEM',
    status: 'ACTIVE',
    createdBy: 'system_admin',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rpt_tpl_finance_executive',
    nameEn: 'Finance & Accounts Receivable Executive Statement',
    nameAr: 'البيان المالي التنفيذي وإدارة الذمم المدينة',
    descriptionEn: 'Authoritative financial performance statement covering billing revenue, AR outstanding balance, and collection ratios.',
    descriptionAr: 'بيان الأداء المالي المعتمد لبيان الإيرادات المفلترة والذمم المدينة ومعدلات التحصيل.',
    resource: 'finance',
    domain: 'FINANCE',
    metricIds: ['fin_invoiced_revenue', 'fin_recognized_revenue', 'fin_outstanding_ar', 'fin_ar_overdue'],
    dimensions: ['status', 'currency'],
    parameters: [
      {
        id: 'dateRange',
        nameEn: 'Fiscal Period',
        nameAr: 'الفترة المالية',
        type: 'DATE_RANGE',
        targetFilterKey: 'dateRange',
      },
      {
        id: 'currency',
        nameEn: 'Reporting Currency',
        nameAr: 'عملة التقرير المالي',
        type: 'SELECT',
        targetFilterKey: 'currency',
        defaultValue: 'SAR',
        allowedValues: [
          { value: 'SAR', labelEn: 'Saudi Riyal (SAR)', labelAr: 'ريال سعودي' },
          { value: 'USD', labelEn: 'US Dollar (USD)', labelAr: 'دولار أمريكي' },
          { value: 'AED', labelEn: 'UAE Dirham (AED)', labelAr: 'درهم إماراتي' },
          { value: 'EUR', labelEn: 'Euro (EUR)', labelAr: 'يورو' },
        ],
      },
    ],
    sections: [
      {
        id: 'sec_fin_kpi',
        type: 'KPI_SUMMARY',
        titleEn: 'Financial Ledger & AR Overview',
        titleAr: 'ملخص السجل المالي والذمم المدينة',
        metricIds: ['fin_invoiced_revenue', 'fin_recognized_revenue', 'fin_outstanding_ar', 'fin_ar_overdue'],
      },
      {
        id: 'sec_fin_status',
        type: 'GROUPED_TABLE',
        titleEn: 'Invoicing & Receivables Status',
        titleAr: 'حالة الفواتير والمستحقات المالي',
        dimension: 'status',
      },
    ],
    outputFormats: ['PDF', 'CSV', 'XLSX'],
    requiredPermissions: ['analytics:view', 'finance:view'],
    visibility: 'SYSTEM',
    status: 'ACTIVE',
    createdBy: 'system_admin',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rpt_tpl_control_tower_exceptions',
    nameEn: 'Control Tower Live Exception & SLA Performance Audit',
    nameAr: 'تقرير برج التحكم للاستثناءات والالتزام بـ SLA',
    descriptionEn: 'Live operational analysis of active transportation exceptions, critical incidents, and SLA resolution performance.',
    descriptionAr: 'تحليل تشغيلي مباشر لتنبيهات برج التحكم، الاستثناءات الحرجة، ومعدلات معالجة SLA.',
    resource: 'control_tower',
    domain: 'OPERATIONS',
    metricIds: ['ct_active_shipments', 'ct_open_exceptions', 'ct_critical_exceptions', 'ct_resolution_rate', 'ct_otd_rate', 'ct_logistics_health_score'],
    dimensions: ['category', 'severity', 'stage'],
    parameters: [
      {
        id: 'dateRange',
        nameEn: 'Monitoring Period',
        nameAr: 'فترة المراقبة',
        type: 'DATE_RANGE',
        targetFilterKey: 'dateRange',
      },
    ],
    sections: [
      {
        id: 'sec_ct_kpi',
        type: 'KPI_SUMMARY',
        titleEn: 'Control Tower Operational Health',
        titleAr: 'مؤشرات برج التحكم المباشرة',
        metricIds: ['ct_active_shipments', 'ct_open_exceptions', 'ct_critical_exceptions', 'ct_resolution_rate', 'ct_otd_rate', 'ct_logistics_health_score'],
      },
      {
        id: 'sec_ct_severity',
        type: 'GROUPED_TABLE',
        titleEn: 'Exceptions Breakdown by Severity',
        titleAr: 'تصنيف الاستثناءات حسب درجة الخطورة',
        dimension: 'severity',
      },
      {
        id: 'sec_ct_category',
        type: 'GROUPED_TABLE',
        titleEn: 'Exceptions Breakdown by Category',
        titleAr: 'تصنيف الاستثناءات حسب نوع العائق',
        dimension: 'category',
      },
    ],
    outputFormats: ['PDF', 'CSV', 'XLSX'],
    requiredPermissions: ['analytics:view', 'control_tower:view'],
    visibility: 'SYSTEM',
    status: 'ACTIVE',
    createdBy: 'system_admin',
    version: 1,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
]);
