/**
 * AJA INTERNATIONAL LOGISTICS — Data View Resource Adapters
 * Phase: Enterprise UI System
 * Module: Data Views, Saved Views & Personalization (STEP 05.16)
 * Version: 1.0
 */

import { DataViewResourceAdapter, EnterpriseDataView } from '../../types/dataViewFramework';
import { DATA_EXCHANGE_LIMITS } from '../../types/dataTransferFramework';

const nowISO = new Date().toISOString();

export const SHIPMENTS_RESOURCE_ADAPTER: DataViewResourceAdapter = {
  resource: 'shipments',
  labelEn: 'Shipments & Waybills',
  labelAr: 'إدارة وتتبع الشحنات وبوالص الشحن',
  allowedFilters: ['status', 'origin', 'destination', 'serviceType', 'carrierId', 'customerId', 'dateRange'],
  allowedSortFields: ['trackingNumber', 'createdAt', 'eta', 'status', 'customerName'],
  requiredColumns: ['trackingNumber'],
  defaultColumns: ['trackingNumber', 'customerName', 'serviceType', 'route', 'status', 'currentLocation'],
  availableColumns: [
    { id: 'trackingNumber', labelEn: 'Tracking Number', labelAr: 'رقم التتبع', required: true, defaultVisible: true },
    { id: 'customerName', labelEn: 'Customer Name', labelAr: 'اسم العميل', defaultVisible: true },
    { id: 'serviceType', labelEn: 'Service Type', labelAr: 'نوع الخدمة', defaultVisible: true },
    { id: 'route', labelEn: 'Origin & Destination', labelAr: 'المصدر والوجهة', defaultVisible: true },
    { id: 'status', labelEn: 'Status', labelAr: 'الحالة الحالية', defaultVisible: true },
    { id: 'currentLocation', labelEn: 'Current Location', labelAr: 'الموقع الحالي', defaultVisible: true },
    { id: 'eta', labelEn: 'Estimated Arrival (ETA)', labelAr: 'الموعد المتوقع للوصول', defaultVisible: false },
    { id: 'weightKg', labelEn: 'Weight (kg)', labelAr: 'الوزن (كجم)', defaultVisible: false },
    { id: 'createdAt', labelEn: 'Created Date', labelAr: 'تاريخ الإنشاء', defaultVisible: false },
  ],
  defaultDensity: 'comfortable',
  defaultPageSize: 25,
  systemDefaultView: {
    id: 'system-default-shipments',
    schemaVersion: 1,
    resource: 'shipments',
    nameEn: 'All Active Shipments',
    nameAr: 'جميع الشحنات النشطة',
    descriptionEn: 'Default system operational view for live logistics tracking',
    descriptionAr: 'العرض الافتراضي للنظام لمتابعة الشحنات المباشرة',
    ownerType: 'SYSTEM',
    visibility: 'SYSTEM',
    isDefault: true,
    isSystem: true,
    query: {
      search: '',
      filters: {},
      sort: { field: 'createdAt', direction: 'desc' },
      pageSize: 25,
    },
    table: {
      visibleColumns: ['trackingNumber', 'customerName', 'serviceType', 'route', 'status', 'currentLocation'],
      columnOrder: ['trackingNumber', 'customerName', 'serviceType', 'route', 'status', 'currentLocation'],
      density: 'comfortable',
    },
    createdAt: nowISO,
    updatedAt: nowISO,
  },
  dataTransferCapabilities: {
    resource: 'shipments',
    supportedExportFormats: ['csv', 'xlsx', 'excel', 'json', 'pdf'],
    supportedImportFormats: ['csv', 'json'],
    maxSynchronousExportRecords: DATA_EXCHANGE_LIMITS.MAX_SYNCHRONOUS_RECORDS,
    maxSynchronousImportRows: DATA_EXCHANGE_LIMITS.MAX_IMPORT_ROWS,
    primaryKey: 'id',
    uniqueLookupKeys: ['trackingNumber', 'referenceNumber'],
    supportedDuplicateStrategies: ['SKIP', 'OVERWRITE', 'CREATE_COPY'],
    exportPermission: 'shipments.export',
    importPermission: 'shipments.import',
    exportableFields: [
      { id: 'id', key: 'id', labelEn: 'Shipment ID', labelAr: 'معرف الشحنة', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'trackingNumber', key: 'trackingNumber', labelEn: 'Tracking Number', labelAr: 'رقم التتبع', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'originCity', key: 'originCity', labelEn: 'Origin City', labelAr: 'مدينة المبدأ', type: 'string', exportable: true, isDefault: true },
      { id: 'destinationCity', key: 'destinationCity', labelEn: 'Destination City', labelAr: 'مدينة الوصول', type: 'string', exportable: true, isDefault: true },
      { id: 'currentStatus', key: 'currentStatus', labelEn: 'Status', labelAr: 'الحالة', type: 'enum', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'carrierPartner', key: 'carrierPartner', labelEn: 'Carrier Partner', labelAr: 'الناقل اللوجستي', type: 'string', exportable: true, isDefault: true },
      { id: 'senderName', key: 'senderName', labelEn: 'Sender Name', labelAr: 'اسم المرسل', type: 'string', exportable: true, isDefault: true },
      { id: 'recipientName', key: 'recipientName', labelEn: 'Recipient Name', labelAr: 'اسم المستلم', type: 'string', exportable: true, isDefault: true },
      { id: 'recipientPhone', key: 'recipientPhone', labelEn: 'Recipient Phone', labelAr: 'رقم هاتف المستلم', type: 'string', exportable: true, isDefault: false, sensitive: true, requiredPermission: 'shipments.sensitive_view' },
      { id: 'weightKg', key: 'weightKg', labelEn: 'Weight (kg)', labelAr: 'الوزن (كجم)', type: 'number', exportable: true, isDefault: true },
      { id: 'declaredValueSar', key: 'declaredValueSar', labelEn: 'Declared Value (SAR)', labelAr: 'القيمة المصرحة (ريال)', type: 'number', exportable: true, isDefault: true },
      { id: 'serviceType', key: 'serviceType', labelEn: 'Service Type', labelAr: 'نوع الخدمة', type: 'string', exportable: true, isDefault: true },
      { id: 'createdAt', key: 'createdAt', labelEn: 'Created At', labelAr: 'تاريخ الإنشاء', type: 'date', exportable: true, isDefault: false },
    ],
    importableFields: [
      { field: 'trackingNumber', labelEn: 'Tracking Number', labelAr: 'رقم التتبع', required: true, type: 'string', allowImport: true, duplicateKeyParticipation: true },
      { field: 'originCity', labelEn: 'Origin City', labelAr: 'مدينة المبدأ', required: false, type: 'string', allowImport: true },
      { field: 'destinationCity', labelEn: 'Destination City', labelAr: 'مدينة الوصول', required: false, type: 'string', allowImport: true },
      { field: 'currentStatus', labelEn: 'Status', labelAr: 'الحالة', required: true, type: 'enum', allowImport: true },
      { field: 'senderName', labelEn: 'Sender Name', labelAr: 'اسم المرسل', required: false, type: 'string', allowImport: true },
      { field: 'recipientName', labelEn: 'Recipient Name', labelAr: 'اسم المستلم', required: false, type: 'string', allowImport: true },
      { field: 'weightKg', labelEn: 'Weight (kg)', labelAr: 'الوزن (كجم)', required: false, type: 'number', allowImport: true },
    ],
  },
};

export const CUSTOMERS_RESOURCE_ADAPTER: DataViewResourceAdapter = {
  resource: 'customers',
  labelEn: 'Customer Directory',
  labelAr: 'إدارة وسجلات العملاء',
  allowedFilters: ['status', 'companyName', 'accountType', 'creditLimit', 'dateRange'],
  allowedSortFields: ['displayName', 'companyName', 'email', 'quotesCount', 'shipmentsCount', 'createdAt'],
  requiredColumns: ['displayName'],
  defaultColumns: ['displayName', 'companyName', 'phone', 'email', 'quotesCount', 'shipmentsCount', 'status'],
  availableColumns: [
    { id: 'displayName', labelEn: 'Customer Name', labelAr: 'اسم العميل', required: true, defaultVisible: true },
    { id: 'companyName', labelEn: 'Company', labelAr: 'اسم الشركة', defaultVisible: true },
    { id: 'phone', labelEn: 'Phone Number', labelAr: 'رقم الجوال', defaultVisible: true },
    { id: 'email', labelEn: 'Email Address', labelAr: 'البريد الإلكتروني', defaultVisible: true },
    { id: 'quotesCount', labelEn: 'Quotes', labelAr: 'طلبات العروض', defaultVisible: true },
    { id: 'shipmentsCount', labelEn: 'Active Shipments', labelAr: 'الشحنات النشطة', defaultVisible: true },
    { id: 'status', labelEn: 'Account Status', labelAr: 'حالة الحساب', defaultVisible: true },
    { id: 'createdAt', labelEn: 'Joined Date', labelAr: 'تاريخ التسجيل', defaultVisible: false },
  ],
  defaultDensity: 'comfortable',
  defaultPageSize: 25,
  systemDefaultView: {
    id: 'system-default-customers',
    schemaVersion: 1,
    resource: 'customers',
    nameEn: 'All Customer Accounts',
    nameAr: 'سجل العملاء العام',
    descriptionEn: 'Default master catalog of customer accounts and profiles',
    descriptionAr: 'العرض القياسي لسجلات وحسابات العملاء',
    ownerType: 'SYSTEM',
    visibility: 'SYSTEM',
    isDefault: true,
    isSystem: true,
    query: {
      search: '',
      filters: {},
      sort: { field: 'displayName', direction: 'asc' },
      pageSize: 25,
    },
    table: {
      visibleColumns: ['displayName', 'companyName', 'phone', 'email', 'quotesCount', 'shipmentsCount', 'status'],
      columnOrder: ['displayName', 'companyName', 'phone', 'email', 'quotesCount', 'shipmentsCount', 'status'],
      density: 'comfortable',
    },
    createdAt: nowISO,
    updatedAt: nowISO,
  },
  dataTransferCapabilities: {
    resource: 'customers',
    supportedExportFormats: ['csv', 'xlsx', 'excel', 'json', 'pdf'],
    supportedImportFormats: ['csv', 'json'],
    maxSynchronousExportRecords: DATA_EXCHANGE_LIMITS.MAX_SYNCHRONOUS_RECORDS,
    maxSynchronousImportRows: DATA_EXCHANGE_LIMITS.MAX_IMPORT_ROWS,
    primaryKey: 'id',
    uniqueLookupKeys: ['email', 'vatNumber', 'commercialRegistration'],
    supportedDuplicateStrategies: ['SKIP', 'OVERWRITE', 'CREATE_COPY'],
    exportPermission: 'customers.export',
    importPermission: 'customers.import',
    exportableFields: [
      { id: 'id', key: 'id', labelEn: 'Customer ID', labelAr: 'معرف العميل', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'companyName', key: 'companyName', labelEn: 'Company Name', labelAr: 'اسم الشركة', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'contactPerson', key: 'contactPerson', labelEn: 'Contact Person', labelAr: 'الشخص المسؤول', type: 'string', exportable: true, isDefault: true },
      { id: 'email', key: 'email', labelEn: 'Email Address', labelAr: 'البريد الإلكتروني', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'phone', key: 'phone', labelEn: 'Phone Number', labelAr: 'رقم الهاتف', type: 'string', exportable: true, isDefault: true },
      { id: 'vatNumber', key: 'vatNumber', labelEn: 'VAT Number', labelAr: 'الرقم الضريبي', type: 'string', exportable: true, isDefault: true },
      { id: 'commercialRegistration', key: 'commercialRegistration', labelEn: 'CR Number', labelAr: 'السجل التجاري', type: 'string', exportable: true, isDefault: false, sensitive: true },
      { id: 'accountStatus', key: 'accountStatus', labelEn: 'Account Status', labelAr: 'حالة الحساب', type: 'enum', exportable: true, isDefault: true },
      { id: 'city', key: 'city', labelEn: 'City', labelAr: 'المدينة', type: 'string', exportable: true, isDefault: true },
      { id: 'creditLimitSar', key: 'creditLimitSar', labelEn: 'Credit Limit (SAR)', labelAr: 'الحد الائتماني (ريال)', type: 'number', exportable: true, isDefault: true, sensitive: true, requiredPermission: 'customers.financial_view' },
    ],
    importableFields: [
      { field: 'companyName', labelEn: 'Company Name', labelAr: 'اسم الشركة', required: true, type: 'string', allowImport: true, duplicateKeyParticipation: true },
      { field: 'contactPerson', labelEn: 'Contact Person', labelAr: 'الشخص المسؤول', required: false, type: 'string', allowImport: true },
      { field: 'email', labelEn: 'Email Address', labelAr: 'البريد الإلكتروني', required: true, type: 'string', allowImport: true, duplicateKeyParticipation: true },
      { field: 'phone', labelEn: 'Phone Number', labelAr: 'رقم الهاتف', required: false, type: 'string', allowImport: true },
      { field: 'vatNumber', labelEn: 'VAT Number', labelAr: 'الرقم الضريبي', required: false, type: 'string', allowImport: true, duplicateKeyParticipation: true },
      { field: 'city', labelEn: 'City', labelAr: 'المدينة', required: false, type: 'string', allowImport: true },
    ],
  },
};

export const QUOTES_RESOURCE_ADAPTER: DataViewResourceAdapter = {
  resource: 'quotes',
  labelEn: 'Quotes & Commercial Offers',
  labelAr: 'طلبات العروض والأسعار التجارية',
  allowedFilters: ['status', 'mode', 'origin', 'destination', 'customerId', 'dateRange'],
  allowedSortFields: ['quoteNumber', 'createdAt', 'estimatedCost', 'status'],
  requiredColumns: ['quoteNumber'],
  defaultColumns: ['quoteNumber', 'customerName', 'mode', 'route', 'estimatedCost', 'status'],
  availableColumns: [
    { id: 'quoteNumber', labelEn: 'Quote Number', labelAr: 'رقم العرض', required: true, defaultVisible: true },
    { id: 'customerName', labelEn: 'Customer Name', labelAr: 'اسم العميل', defaultVisible: true },
    { id: 'mode', labelEn: 'Transport Mode', labelAr: 'وسيلة النقل', defaultVisible: true },
    { id: 'route', labelEn: 'Route', labelAr: 'المسار (المصدر ← الوجهة)', defaultVisible: true },
    { id: 'estimatedCost', labelEn: 'Estimated Cost', labelAr: 'التكلفة التقديرية', defaultVisible: true },
    { id: 'status', labelEn: 'Status', labelAr: 'حالة العرض', defaultVisible: true },
    { id: 'createdAt', labelEn: 'Requested Date', labelAr: 'تاريخ الطلب', defaultVisible: false },
  ],
  defaultDensity: 'comfortable',
  defaultPageSize: 25,
  systemDefaultView: {
    id: 'system-default-quotes',
    schemaVersion: 1,
    resource: 'quotes',
    nameEn: 'Active Commercial Quotes',
    nameAr: 'جميع عروض الأسعار النشطة',
    descriptionEn: 'Default listing of active rate requests and custom quotes',
    descriptionAr: 'العرض الافتراضي العروض الأسعار النشطة والطلبات المعلقة',
    ownerType: 'SYSTEM',
    visibility: 'SYSTEM',
    isDefault: true,
    isSystem: true,
    query: {
      search: '',
      filters: {},
      sort: { field: 'createdAt', direction: 'desc' },
      pageSize: 25,
    },
    table: {
      visibleColumns: ['quoteNumber', 'customerName', 'mode', 'route', 'estimatedCost', 'status'],
      columnOrder: ['quoteNumber', 'customerName', 'mode', 'route', 'estimatedCost', 'status'],
      density: 'comfortable',
    },
    createdAt: nowISO,
    updatedAt: nowISO,
  },
  dataTransferCapabilities: {
    resource: 'quotes',
    supportedExportFormats: ['csv', 'xlsx', 'excel', 'json', 'pdf'],
    supportedImportFormats: ['csv', 'json'],
    maxSynchronousExportRecords: DATA_EXCHANGE_LIMITS.MAX_SYNCHRONOUS_RECORDS,
    maxSynchronousImportRows: DATA_EXCHANGE_LIMITS.MAX_IMPORT_ROWS,
    primaryKey: 'id',
    uniqueLookupKeys: ['quoteNumber'],
    supportedDuplicateStrategies: ['SKIP', 'OVERWRITE', 'CREATE_COPY'],
    exportPermission: 'quotes.export',
    importPermission: 'quotes.import',
    exportableFields: [
      { id: 'id', key: 'id', labelEn: 'Quote ID', labelAr: 'معرف العرض', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'quoteNumber', key: 'quoteNumber', labelEn: 'Quote Number', labelAr: 'رقم عرض السعر', type: 'string', exportable: true, isDefault: true, isRequiredForImport: true },
      { id: 'customerName', key: 'customerName', labelEn: 'Customer Name', labelAr: 'اسم العميل', type: 'string', exportable: true, isDefault: true },
      { id: 'originPort', key: 'originPort', labelEn: 'Origin Port', labelAr: 'ميناء المبدأ', type: 'string', exportable: true, isDefault: true },
      { id: 'destinationPort', key: 'destinationPort', labelEn: 'Destination Port', labelAr: 'ميناء الوصول', type: 'string', exportable: true, isDefault: true },
      { id: 'quotedAmountSar', key: 'quotedAmountSar', labelEn: 'Quoted Amount (SAR)', labelAr: 'المبلغ المعروض (ريال)', type: 'number', exportable: true, isDefault: true, sensitive: false },
      { id: 'marginPercentage', key: 'marginPercentage', labelEn: 'Profit Margin (%)', labelAr: 'هامش الربح (%)', type: 'number', exportable: true, isDefault: false, sensitive: true, requiredPermission: 'quotes.financial_view' },
      { id: 'status', key: 'status', labelEn: 'Status', labelAr: 'الحالة', type: 'enum', exportable: true, isDefault: true },
      { id: 'validUntil', key: 'validUntil', labelEn: 'Valid Until', labelAr: 'صالح حتى', type: 'date', exportable: true, isDefault: true },
    ],
    importableFields: [
      { field: 'quoteNumber', labelEn: 'Quote Number', labelAr: 'رقم عرض السعر', required: true, type: 'string', allowImport: true, duplicateKeyParticipation: true },
      { field: 'customerName', labelEn: 'Customer Name', labelAr: 'اسم العميل', required: false, type: 'string', allowImport: true },
      { field: 'originPort', labelEn: 'Origin Port', labelAr: 'ميناء المبدأ', required: false, type: 'string', allowImport: true },
      { field: 'destinationPort', labelEn: 'Destination Port', labelAr: 'ميناء الوصول', required: false, type: 'string', allowImport: true },
      { field: 'quotedAmountSar', labelEn: 'Quoted Amount (SAR)', labelAr: 'المبلغ المعروض (ريال)', required: false, type: 'number', allowImport: true },
    ],
  },
};

export const ANALYTICS_RESOURCE_ADAPTER: DataViewResourceAdapter = {
  resource: 'analytics',
  labelEn: 'Analytics & Executive Dashboards',
  labelAr: 'تقارير ولوحات المتابعة التنفيذية',
  allowedFilters: ['status', 'serviceType', 'origin', 'destination', 'customerSegment', 'currency', 'dateRange', 'domain', 'resource'],
  allowedSortFields: ['id', 'createdAt', 'updatedAt', 'name'],
  requiredColumns: ['id'],
  defaultColumns: ['id', 'name', 'status', 'createdAt'],
  availableColumns: [
    { id: 'id', labelEn: 'ID', labelAr: 'المعرف', required: true, defaultVisible: true },
    { id: 'name', labelEn: 'Dashboard Name', labelAr: 'اسم اللوحة', defaultVisible: true },
    { id: 'status', labelEn: 'Status', labelAr: 'الحالة', defaultVisible: true },
    { id: 'createdAt', labelEn: 'Created At', labelAr: 'تاريخ الإنشاء', defaultVisible: true },
  ],
  defaultDensity: 'comfortable',
  defaultPageSize: 25,
  systemDefaultView: {
    id: 'system-default-analytics',
    schemaVersion: 1,
    resource: 'analytics',
    nameEn: 'Executive Logistics Overview',
    nameAr: 'العرض اللوجستي التنفيذي العام',
    descriptionEn: 'System default executive reporting view',
    descriptionAr: 'عرض التقارير التنفيذية القياسي بالنظام',
    ownerType: 'SYSTEM',
    visibility: 'SYSTEM',
    isDefault: true,
    isSystem: true,
    query: {
      search: '',
      filters: {},
      sort: { field: 'createdAt', direction: 'desc' },
      pageSize: 25,
      analytics: {
        selectedMetricIds: ['shipment_count', 'customer_count', 'quote_count'],
        resource: 'shipments',
      },
    },
    table: {
      visibleColumns: ['id', 'name', 'status', 'createdAt'],
      columnOrder: ['id', 'name', 'status', 'createdAt'],
      density: 'comfortable',
    },
    createdAt: nowISO,
    updatedAt: nowISO,
  },
};

export const RESOURCE_ADAPTER_REGISTRY: Record<string, DataViewResourceAdapter> = {
  shipments: SHIPMENTS_RESOURCE_ADAPTER,
  customers: CUSTOMERS_RESOURCE_ADAPTER,
  quotes: QUOTES_RESOURCE_ADAPTER,
  analytics: ANALYTICS_RESOURCE_ADAPTER,
};

/**
 * Retrieves resource adapter for a given resource or builds a dynamic generic adapter
 */
export function getResourceAdapter(resource: string): DataViewResourceAdapter {
  if (RESOURCE_ADAPTER_REGISTRY[resource]) {
    return RESOURCE_ADAPTER_REGISTRY[resource];
  }

  // Fallback Generic Adapter for any un-registered resource
  return {
    resource,
    labelEn: `${resource.charAt(0).toUpperCase()}${resource.slice(1)} Registry`,
    labelAr: `سجل ${resource}`,
    allowedFilters: ['status', 'dateRange', 'type', 'category'],
    allowedSortFields: ['id', 'createdAt', 'updatedAt', 'name', 'status'],
    requiredColumns: ['id'],
    defaultColumns: ['id', 'name', 'status', 'createdAt'],
    availableColumns: [
      { id: 'id', labelEn: 'ID', labelAr: 'المعرف', required: true, defaultVisible: true },
      { id: 'name', labelEn: 'Name', labelAr: 'الاسم', defaultVisible: true },
      { id: 'status', labelEn: 'Status', labelAr: 'الحالة', defaultVisible: true },
      { id: 'createdAt', labelEn: 'Created At', labelAr: 'تاريخ الإنشاء', defaultVisible: true },
    ],
    defaultDensity: 'comfortable',
    defaultPageSize: 25,
    systemDefaultView: {
      id: `system-default-${resource}`,
      schemaVersion: 1,
      resource,
      nameEn: `All ${resource.charAt(0).toUpperCase()}${resource.slice(1)}`,
      nameAr: `جميع سجلات ${resource}`,
      descriptionEn: 'System default data view',
      descriptionAr: 'عرض النظام الافتراضي',
      ownerType: 'SYSTEM',
      visibility: 'SYSTEM',
      isDefault: true,
      isSystem: true,
      query: {
        search: '',
        filters: {},
        sort: { field: 'createdAt', direction: 'desc' },
        pageSize: 25,
      },
      table: {
        visibleColumns: ['id', 'name', 'status', 'createdAt'],
        columnOrder: ['id', 'name', 'status', 'createdAt'],
        density: 'comfortable',
      },
      createdAt: nowISO,
      updatedAt: nowISO,
    },
  };
}
